apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
  selector:
    app: nginx # Targets your Nginx deployment
  ports:
    - protocol: TCP
      port: 80 # The port the load balancer listens on
      targetPort: 80 # The target port on the pods to send traffic to
